### PR TITLE
Execute scripted tests on travis

### PR DESCRIPTION
**Pull request by lustefaniak**

### CODE REVIEW

**Comment by lustefaniak** [comment]
Fails due to `org.scoverage#scalac-scoverage-plugin_2.10;1.2.0-SNAPSHOT: not found`

**Comment by gslowikowski** [comment]
All scripted tests need setting similar to the plugin itself, I think (didn't test it myself):
```scala
resolvers ++= {
  if (isSnapshot.value) Seq(Resolver.sonatypeRepo("snapshots"))
  else Seq.empty
}
```

Add it, test, and if it works, commit and squash.

**Comment by gslowikowski** [comment]
You can remove `test` from Travis script. There are no unit tests.

**Comment by gslowikowski** [comment]
`aggregate` scripted test was fixed in https://github.com/scoverage/sbt-scoverage/pull/175/commits/e110f198e8630fe739d580bb88bb291cbb2348e9, you can copy from that commit, it added some checks.

**Comment by lustefaniak** [comment]
RDY

**Pull request merged**
