### PR TITLE
Support file and package exclusions for Scala 3.4.2+

### LINKED ISSUE #525: Package / file exclusion does not work with Scala 3
Hi there. There seems that some coverage settings (primarily `coverageExcludedPackages` and `coverageExcludedFiles`, but I believe some other ones might be affected) are not working with Scala 3.

The easiest way to reproduce is by cloning the [sbt-scoverage-samples repo](https://github.com/scoverage/sbt-scoverage-samples), adding the following line to `build.sbt`:
```
coverageExcludedPackages := ".*"
```
and then running 
```
sbt coverage +test +coverageReport
```

This yields the following:

Scala 2:
```
[success] Total time: 13 s, completed 23 Dec 2023, 12:55:46 pm
[info] Statement coverage.: 100.00%
[info] Branch coverage....: 100.00%
[info] Coverage reports completed
```

Scala 3:
```
[info] Statement coverage.: 65.20%
[info] Branch coverage....: 33.33%
[info] Coverage reports completed
```

### PR DESCRIPTION
**Pull request by jozic**
fixes #525

### CODE REVIEW

**Comment by jozic** [comment]
@ckipp01 please review when you have a minute

**Comment by TonioGela** [comment]
+1 on this

**Review by ckipp01 — APPROVED** [review]
This looks great, thanks @jozic! I left a nit, but it's not a huge deal, probably helpful for us to track in the future. I'll go ahead and merge now and then cut a release.

**Comment by ckipp01** [comment]
Sorry had an issue with the release due to some sonatype changes, but everything should be good to go now and released 🚀

**Pull request merged**
