### PR TITLE
Add support for scala.js runtime

### PR DESCRIPTION
**Pull request by lustefaniak**

### CODE REVIEW

**Comment by gslowikowski** [comment]
Ready to merge?

**Comment by lustefaniak** [comment]
RDY, I tested it locally and scala.js works perfectly. 
It fails for me on `scripted scoverage/aggregate`, but that is also failing on `master` I think `check` script misses `coverageReport` which is not executed after `test` anymore (and I think in the past it was not needed).

**Comment by lustefaniak** [comment]
Would be great to have scripted tests execute on Travis, I will fix that `scripted scoverage/aggregate` in next PR.

**Comment by gslowikowski** [comment]
OK

**Comment by gslowikowski** [comment]
Some time ago we discussed on Gitter and [here](https://github.com/scoverage/sbt-scoverage/pull/182#r78653723) about adding `sbt-scalajs` plugin and using `%%%` operator.

In Play! Framework Twirl module they went this way: https://github.com/playframework/twirl/commit/104128a41ed3cecfd329f1721d5f7ae4cf0286d7 (look at `build.sbt` changes).

**Comment by lustefaniak** [comment]
Can you please explain what you mean? I think I don't undertand, do you mean adding addSbtPlugin in build? That doesn't solve the problem at all, as operator %%% used in that context has completly different meaning than operator used in user project (eg. different versions)

**Comment by gslowikowski** [comment]
We talked about using:
```scala
        OrgScoverage %%% ScalacRuntimeArtifact % coverageScalacPluginVersion.value,
```
instead of
```scala
        OrgScoverage %% (ScalacRuntimeArtifact + optionalScalaJsSuffix(libraryDependencies.value)) % coverageScalacPluginVersion.value,
```
[here](https://github.com/scoverage/sbt-scoverage/blob/v1.4.0/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L36)

**Comment by lustefaniak** [comment]
Yes, but that approach would still require pulling in sbt-scalajs plugin. I checked its source code and there is nothing we could reuse, everything depends on hardcoded scala.js binary version.

**Comment by lustefaniak** [comment]
Hi @sjrd can you please confirm if such approach should support future version of scala.js? Or how we could improve that without adding sbt-scalajs do dependencies?

**Comment by sjrd** [comment]
It will work as long as we're in the 0.6.x series. When we switch to the 1.x.y series, the binary _sjs version will be only the major version, so `_sjs1` (and not `_sjs1.0`).

**Pull request merged**
