### PR TITLE
add sbt 1.0.0-RC3 support, fixes #216

### LINKED ISSUE #216: Support For sbt 1.0
Currently scoverage is only available for sbt 0.13. Can we get a released version for sbt 1.0?

### PR DESCRIPTION
**Pull request by rockjam**
This PR adds support for sbt 1.0.0-RC2 which is close to upcoming 1.0.0 release

### CODE REVIEW

**Comment by rockjam** [comment]
I guess we should run tests for both sbt versions now

**Comment by rockjam** [comment]
scalajs test fails for 0.13 for some reason. Both on CI and my local machine

**Comment by rockjam** [comment]
Also, it's not possible to run scalajs tests for 1.0.0-RC2 until scala-js/scala-js#3075 released as scalajs doesn't support sbt 1.0.0-RC2 yet

**Comment by rockjam** [comment]
> scalajs test fails for 0.13 for some reason. Both on CI and my local machine
This one is fixed

**Comment by rockjam** [comment]
All tests passed at CI. Also upgraded sbt versions to 0.13.16 and 1.0.0-RC3 respectively

**Comment by gslowikowski** [comment]
Hi @rockjam 

Thank you for your PR. I've tested it. The code can be slightly simplified. Could you change the line:
```
        val scoverageDeps: Seq[File] = Deps.scoverageDeps(updateReport, ScoveragePluginConfig.name)
```
to
```
        val scoverageDeps: Seq[File] = updateReport matching configurationFilter(ScoveragePluginConfig.name)
```

and remove `src/main/scala-sbt-0.13` and `src/main/scala-sbt-1.0` directories?

**Comment by rockjam** [comment]
@gslowikowski Done! Thanks for advice

**Comment by larsrh** [comment]
A release for sbt 1.0.x would be much appreciated! There are many builds who use this.

**Pull request merged**
