### PR TITLE
added TC branch coverage reporting

### LINKED ISSUE #172: Teamcity stats are incomplete
For code coverage summary (with diffs from previous build) to appear in overview tab,
the following stats must be sent:

a) Lines or Classes 
b) Blocks 
c) Statements or Methods.

As per [current code](https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L198)

Only statements stats are being sent:

```
    log.info(statsKeyValue("CodeCoverageAbsSCovered", coverage.invokedStatementCount))
    log.info(statsKeyValue("CodeCoverageAbsSTotal", coverage.statementCount))
```

But blocks are sent as custom stat:
`CodeCoverageBranch`

So, 2 stats are missing at the moment:
1) Block coverage stats must be sent as:

```
##teamcity[buildStatisticValue key='CodeCoverageB' value=' <value>'] 
##teamcity[buildStatisticValue key='CodeCoverageAbsBCovered' value='<value>']
##teamcity[buildStatisticValue key='CodeCoverageAbsBTotal' value='<value>']
```

2) Lines or Classes. Lines can be excluded, in favor of statements stats. Thus classes total coverage must be calculated and sent, so that teamcity coverage summary could appear on build overview tab:

```
##teamcity[buildStatisticValue key='CodeCoverageC' value='<value>']
##teamcity[buildStatisticValue key='CodeCoverageAbsCCovered' value='<value>']
##teamcity[buildStatisticValue key='CodeCoverageAbsCTotal' value='<value>'] 
```

### PR DESCRIPTION
**Pull request by alexnikitchuk**
Partially fixes #172

### CODE REVIEW

**Comment by cbrunnkvist** [comment]
Yup just arrived here after tracking down this problem _and_ proposed solution specifically. Would be nice if it could merge.

**Comment by alexnikitchuk** [comment]
@sksamuel @gslowikowski @BennyHill up

**Comment by ckipp01** [comment]
This is quite old, but is this still desired and up to date? If someone would like to take a look at this I can review.

**Review by ckipp01 — APPROVED** [review]
So looking into the documentation everything seems fine here. I've gone ahead and just committed on top of this to get it across the board.

Thanks for the contribution!

**Pull request merged**
