### PR TITLE
Build CrossVersion.full

### LINKED ISSUE #319: NoSuchMethodError for scala 2.12.13
Error: `java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter`

Reference and all details: https://github.com/sbt/sbt/issues/6251

Error: https://github.com/bitcoin-s/bitcoin-s/pull/2509/checks (credits to https://github.com/sbt/sbt/issues/6251#issuecomment-759674809 / @Christewart)

### PR DESCRIPTION
**Pull request by blast-hardcheese**
Resolves #319, blocked by https://github.com/scoverage/scalac-scoverage-plugin/pull/306

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
@D-Roch I added a PR workflow, but it doesn't appear that actions is enabled here, it would be useful to enable to ensure we don't end up with version slips.

**Comment by D-Roch** [comment]
@blast-hardcheese ok thank you, yes we were using Travis but it no longer triggers as they are shutting down

**Comment by blast-hardcheese** [comment]
@D-Roch This is blocked by https://github.com/scoverage/scalac-scoverage-plugin/pull/306... if this is released without that, users will just get errors attempting to use the sbt plugin

**Comment by blast-hardcheese** [comment]
what needs to happen is the `scalac-scoverage-plugin` must be released first, then the version bumped in this plugin

**Comment by sullis** [comment]
nice PR @blast-hardcheese 🥇

**Pull request merged**
