### PR TITLE
Add coverageScalacPluginVersion setting key

### PR DESCRIPTION
**Pull request by lustefaniak**
Make it easier to change version of scalac-scoverage-plugin dependency

### CODE REVIEW

**Comment by gslowikowski** [comment]
You forgot to change `DefaultScoverageVersion` to `coverageScalacPluginVersion` in `projectSettings` (`libraryDependencies ++= ...` section).

**Comment by lustefaniak** [comment]
@gslowikowski Thanks, I was already pushing fixed version ;)

**Comment by gslowikowski** [comment]
:)

**Comment by gslowikowski** [comment]
LGTM, can I merge it?

**Comment by lustefaniak** [comment]
RDY, I added one scripted test to assert correct behaviour

**Pull request merged**
