### PR TITLE
Uses new containerized Travis build system

### PR DESCRIPTION
**Pull request by migmruiz**
https://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by rorygraves** [comment]
Based on the fact travis actually passes with this I'm going to merge.

**Comment by gslowikowski** [comment]
`+sudo: false` can be removed. False is default value.

This file is very similar to the one in [my Java/Scala/Maven test projects](https://github.com/play2-maven-plugin/play2-maven-test-projects/blob/master/.travis.yml). I have no `sudo` setting.

From Travis docs (above link):

If you see `This job is running on container-based infrastructure` in your build log it means you are already running builds on our new container-based infrastructure.

If you don’t, to use the new infrastructure add the following line to your .travis.yml:

`sudo: false`

Check Travis logs. There is `This job is running on container-based infrastructure` line. [This one](https://s3.amazonaws.com/archive.travis-ci.org/jobs/135035701/log.txt) one is from latest build.

**Comment by rorygraves** [comment]
Whoops - looks like I was a bit hasty on that merge.

**Comment by gslowikowski** [comment]
No, it's OK, removing `sudo` option is just small improvement you can commit separately.

**Comment by rorygraves** [comment]
Yeah I'll drop that in today

**Pull request merged**
