### PR TITLE
Source encoding parametrization - fix for issue scoverage/scalac-scoverage-plugin#134

### PR DESCRIPTION
**Pull request by gslowikowski**
Fix for scoverage/scalac-scoverage-plugin#134

### CODE REVIEW

**Comment by sksamuel** [comment]
Can you get the build to pass before merging.

**Comment by gslowikowski** [comment]
It will not compile until `scalac-scoverage-plugin` PR merge and new snapshot publishing.

**Comment by sksamuel** [comment]
I've merged that now.

**Comment by gslowikowski** [comment]
I've published new snapshot and rerun the build here. Now it passes.

**Pull request merged**
