### PR TITLE
Configure Bintray publishing

### PR DESCRIPTION
**Pull request by pdalpra**
Should be good, although I can't verify without credentials

### CODE REVIEW

**Comment by sksamuel** [comment]
Testing now

**Comment by sksamuel** [comment]
java.lang.RuntimeException: Repository for publishing is not specified.
	at scala.sys.package$.error(package.scala:27)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1470)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.Classpaths$.getPublishTo(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$59.apply(Defaults.scala:1150)
	at sbt.Classpaths$$anonfun$59.apply(Defaults.scala:1150)

**Comment by sksamuel** [comment]
I think its missing this line settings(bintrayPublishSettings: _*).

**Comment by pdalpra** [comment]
It's an AutoPlugin now, so manually adding the settings is not needed anymore

**Comment by sksamuel** [comment]
Ok. But getting that exception if I leave it out.

**Comment by sksamuel** [comment]
Seemed to run the 3rd time, odd

**Comment by pdalpra** [comment]
````
> publish
[info] :: delivering :: org.scoverage#sbt-scoverage;1.3.0 :: 1.3.0 :: release :: Thu Jul 23 11:52:59 CEST 2015
[info] 	delivering ivy file to /Users/pierredalpra/Work/Forks/sbt-scoverage/target/scala-2.10/sbt-0.13/ivy-1.3.0.xml
[info] Main Scala API documentation to /Users/pierredalpra/Work/Forks/sbt-scoverage/target/scala-2.10/sbt-0.13/api...
[warn] No main class detected
[info] Packaging /Users/pierredalpra/Work/Forks/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0.jar ...
[info] Done packaging.
model contains 5 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/pierredalpra/Work/Forks/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0-javadoc.jar ...
[info] Done packaging.
{"message":"This resource requires authentication"}
[trace] Stack trace suppressed: run last *:bintrayEnsureBintrayPackageExists for the full output.
[trace] Stack trace suppressed: run last *:publish for the full output.
[error] (*:bintrayEnsureBintrayPackageExists) was not able to find or create a package for a in Repo(a,sbt-plugins) named sbt-scoverage
[error] (*:publish) error uploading to org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.0/jars/sbt-scoverage.jar: {"message":"This resource requires authentication"}
[error] Total time: 4 s, completed Jul 23, 2015 11:53:02 AM
```

**Comment by sksamuel** [comment]
First run was:

```
sam@sam-xubuntu:~/development/workspace/scoverage/sbt-scoverage$ sbt publish
[info] Loading project definition from /home/sam/development/workspace/scoverage/sbt-scoverage/project
Missing bintray credentials /home/sam/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to sbt-scoverage (in build file:/home/sam/development/workspace/scoverage/sbt-scoverage/)
bintray-sbt requires your bintray credentials.
[warn] Credentials file /home/sam/.bintray/.credentials does not exist
Enter bintray username: [info] Updating {file:/home/sam/development/workspace/scoverage/sbt-scoverage/}sbt-scoverage...
[info] Resolving org.scala-sbt#sbt-launch;0.13.8 ...
[info] Done updating.
[info] :: delivering :: org.scoverage#sbt-scoverage;1.3.0 :: 1.3.0 :: release :: Thu Jul 23 10:45:04 BST 2015
[info] 	delivering ivy file to /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/ivy-1.3.0.xml
[info] Main Scala API documentation to /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/api...
[info] Compiling 2 Scala sources to /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/classes...
model contains 6 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0-javadoc.jar ...
[info] Done packaging.
[info] Packaging /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0.jar ...
[info] Done packaging.
sksamuel
Enter bintray API key (under https://bintray.com/profile/edit): ****************************************
saving credentials to /home/sam/.bintray/.credentials
reload project for sbt setting `publishTo` to take effect
java.lang.RuntimeException: Repository for publishing is not specified.
	at scala.sys.package$.error(package.scala:27)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1470)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.Classpaths$.getPublishTo(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$59.apply(Defaults.scala:1150)
	at sbt.Classpaths$$anonfun$59.apply(Defaults.scala:1150)
```

**Comment by sksamuel** [comment]
Later run was:

```
sam@sam-xubuntu:~/development/workspace/scoverage/sbt-scoverage$ sbt publish
[info] Loading project definition from /home/sam/development/workspace/scoverage/sbt-scoverage/project
[info] Set current project to sbt-scoverage (in build file:/home/sam/development/workspace/scoverage/sbt-scoverage/)
[info] Updating {file:/home/sam/development/workspace/scoverage/sbt-scoverage/}sbt-scoverage...
[info] Resolving org.scala-sbt#sbt-launch;0.13.8 ...
[info] Done updating.
[info] :: delivering :: org.scoverage#sbt-scoverage;1.3.0 :: 1.3.0 :: release :: Thu Jul 23 10:52:06 BST 2015
[info] Main Scala API documentation to /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/api...
[info] 	delivering ivy file to /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/ivy-1.3.0.xml
[info] Packaging /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0.jar ...
[info] Done packaging.
model contains 6 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /home/sam/development/workspace/scoverage/sbt-scoverage/target/scala-2.10/sbt-0.13/sbt-scoverage-1.3.0-javadoc.jar ...
[info] Done packaging.
[info] 	published sbt-scoverage to org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.0/jars/sbt-scoverage.jar
[info] 	published sbt-scoverage to org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.0/srcs/sbt-scoverage-sources.jar
[info] 	published sbt-scoverage to org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.0/docs/sbt-scoverage-javadoc.jar
[info] 	published ivy to org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.0/ivys/ivy.xml
[info] sksamuel/sbt-scoverage@1.3.0 was released
[success] Total time: 23 s, completed 23-Jul-2015 10:52:28
```

**Comment by sksamuel** [comment]
Just have to hope it works and it shows up now:
https://dl.bintray.com/sbt/sbt-plugin-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/

**Comment by sksamuel** [comment]
Ah I missed this bit first time `reload project for sbt setting `publishTo` to take effect`

**Comment by pdalpra** [comment]
Since you pushed to Bintray for the first time, you'll have to ask that your plugins get linked to the sbt-plugins bintray repo (as stated in the doc page you referenced to @D-Roch).
Otherwise, it will only show up on your repo.

**Comment by sksamuel** [comment]
Yeah, I think I did this when I first used bintray ages ago. I've just checked their site and there is an sbt-scoverage-imported project, and *-imported are the mirrors I think.

**Comment by pdalpra** [comment]
Not sure that's it's the same : Gatling's SBT plugins doesn't show up in the '*-imported' project, yet it's published to sbt-plugins-releases.

**Comment by sksamuel** [comment]
Hmmm ok. I'll check again.

**Comment by sksamuel** [comment]
It looks fine. The project says its linked to sbt plugin releases and shows up if you search for scoverage under the sbt aggregate project.

**Pull request merged**
