### PR TITLE
Add support for Scala 3

### PR DESCRIPTION
**Pull request by pikinier20**
related to: https://github.com/lampepfl/dotty/issues/15110

### CODE REVIEW

**Comment by pikinier20** [comment]
@ckipp01

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Thanks for the pr @pikinier20!

So I think instead of having specific instructions for Scala 3 it'd be better to instead just update the code here:

https://github.com/scoverage/sbt-scoverage/blob/73f8f92e41eddc2dad3a7404284b5aa47afaee52/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L158-L172

All the logic is already there to automate the setting up of the `scalacOptions` so the user doesn't have to worry about them. Then the user no matter if they are using Scala 2 or Scala 3 the experience is the same, just use `coverage` or `coverageEnabled` and the plugin will take care of everything. Can we change this pr to update this code instead of having instructions for manual steps the user needs to take?

Also now that we are officially adding support for Scala 3 we should also add a test for this in https://github.com/scoverage/sbt-scoverage/tree/V2/src/sbt-test/scoverage.

You'll also want to update the pr to point towards the V2 branch instead of Main. After we get this merged in I'll probably go ahead and just release the V2 so users won't have to worry about using a milestone release to use it with Scala 3.

**Comment by pikinier20** [comment]
@TheElectronWill Perhaps you want to continue the work here?

I mean, I can do it but my intention was only to move this documentation from Dotty :)

**Comment by pikinier20** [comment]
Just as you proposed, instead of adding documentation, I added necessary scalacOption in plugin. Also, I've added two tests for scala 3. Probably we should wait for Scala 3.2.0-RC1 before merging it because it'll be first stable version which supports `-coverage-out` flag. Perhaps we should check the version and throw a warning if version is not supported?

**Comment by TheElectronWill** [comment]
Sorry, I didn't have the time to add it last week. Kudos for doing it @pikinier20 !

**Pull request closed without merging**
