### PR TITLE
Add autoImport, for easier usage with .sbt files

### PR DESCRIPTION
**Pull request by pdalpra**
This PR enables auto-import of ScoverageKeys in `.sbt` files.

### CODE REVIEW

**Comment by sksamuel** [comment]
Is the autoImport always in scope in sbt 0.13.something?

**Comment by pdalpra** [comment]
Yep (came along the introduction of the AutoPlugins in SBT 0.13.5).

This would mean that users that imported all the keys with a wildcard (e.g. `import scoverage.ScoverageSbtPlugin.ScoverageKeys._` will need to remove that import, or sbt will complain that the keys are imported twice (one time from autoImport, one time from ScoverageKeys directly).

No issues for users that prefixed the keys by `ScoverageKeys.`, they can simply drop the prefix and the import when they want to.

**Comment by sksamuel** [comment]
So its a breaking change. If we do that then we might as well just get rid of ScoverageKeys and rename it?

**Comment by pdalpra** [comment]
having `ScoverageKeys` is still nice IMO, not fond of `import xxx.autoImport._` in `.scala`-based builds, where they are required.
However, moving `ScoverageKeys` out the plugin object could be nice :)

**Comment by sksamuel** [comment]
Ok lets do the latter.

**Comment by pdalpra** [comment]
Sure !
If you're OK with that, I think I'll close that PR to prepare a bigger one, including what we discussed. WDYT ?

**Comment by sksamuel** [comment]
Sounds great.

**Pull request closed without merging**
