### PR TITLE
#132 clarify when reports are generated and when minimums are applied

### LINKED ISSUE #132: Inconsistencies in when reports are generated and when coverageMinimum is applied
Currently, the coverage reports are created:
 * per-project: After a "test" run (see "postTestReport", line 122)
 * per-project: When the "coverageReport" command is called (see line 68)
 * per-build: When the "coverageAggregate" command is called (see line 87)

Currently, the coverage minimum is applied:
 * per-project: After a "test" run (see "postTestReport", line 132)
 * per-build: never

I think that it's confusing to create the reports after a test run when there is now a "" command.

I think this should be changed so that:

The coverage reports are created:
 * per-project: When the "coverageReport" command is called
 * per-build: When the "coverageAggregate" command is called

The coverage minimum is applied:
 * per-project: When the "coverageReport" command is called
 * per-build: When the "coverageAggregate" command is called

Sound OK? I'll prepare a PR, unless you object?

### PR DESCRIPTION
**Pull request by RichardBradley**
Fixes #132

### CODE REVIEW

**Comment by sksamuel** [comment]
Can we split this up as 1.3.2 isn't released yet so updating readme at same time will mean more issues :)

**Comment by RichardBradley** [comment]
> Can we split this up as 1.3.2 isn't released yet so updating readme at same time will mean more issues :)

Sure, I've split the branch into two commits - one with the code changes and one with the README and version changes. Is that what you need, or did you want two separate PRs?

I don't think I understand why though...
The PR includes a version number change, so I would expect the workflow to be something like:
 * PR is merged
 * (for a very short time) the README at https://github.com/scoverage/sbt-scoverage displays the new version number (1.3.2) and the new documentation about when reports are generated. Anyone who tries to use 1.3.2 will be disappointed.
 * 1.3.2 is published, either by you or by your automated build systems
 * The README on github is now correct

Did you want to merge this and not publish it or something? Am I just being dumb?

> https://travis-ci.org/scoverage/sbt-scoverage/builds/76252063

There was a build failure -- I'll check. This test passes for me locally though. I'll look into it.

**Comment by sksamuel** [comment]
Because I can't release until on my proper computer, and I'll get 100
emails guaranteed :)

**Comment by sksamuel** [comment]
I guess I can just leave it parked here until I'm ready.

**Comment by RichardBradley** [comment]
> I guess I can just leave it parked here until I'm ready.

That's what I was expecting :-)

**Comment by RichardBradley** [comment]
> There was a build failure -- I'll check

I'll come back to this tomorrow or later this week.

**Comment by RichardBradley** [comment]
> There was a build failure

Found the problem -- the "scripted" test "bad-coverage" is checking that the coverage minimums are enforced. It ran "`sbt clean coverage test`" and expected a failure.

I've updated it to run "`sbt clean coverage test coverageReport`" as per the new design discussed at the top of this thread.

(I didn't know about the "scripted" sbt tests plugin -- that's pretty useful.)

**Comment by rorygraves** [comment]
@RichardBradley This has a merge conflict, can you please rebase?

**Comment by RichardBradley** [comment]
I've pushed a merge
(Let me know if you'd much rather have a rebase)

**Comment by RichardBradley** [comment]
OK to merge now?

**Comment by sksamuel** [comment]
Thanks richard

**Pull request merged**
