### PR TITLE
Replace mutable var by a Setting and commands to toggle it

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by D-Roch** [comment]
:santa: :+1:

**Comment by sksamuel** [comment]
Can you update the docs too.

**Comment by pdalpra** [comment]
Sure, I'll provide a PR that you can merge after release :)

**Comment by sksamuel** [comment]
That would be awesome thanks.

**Comment by sksamuel** [comment]
1.3.0 is released.

**Comment by gslowikowski** [comment]
@pdalpra why you implemented `coverage` and `coverageOff` as SBT commands (http://www.scala-sbt.org/0.13/docs/Commands.html for reference)? They should be simple tasks IMO.

**Pull request merged**
