### PR TITLE
Avoid removing settings overrides done during the session when executing toggleCoverage

### PR DESCRIPTION
**Pull request by lustefaniak**
This is just a rebase of https://github.com/scoverage/sbt-scoverage/pull/175

### CODE REVIEW

**Comment by gslowikowski** [comment]
Closes #175

**Comment by mtrampont** [comment]
Sorry for the late reply, and thanks for taking care of the rebase.

**Comment by gslowikowski** [comment]
@mtrampont did you find somewhere the solution you proposed or are you the author? It's a little bit complicated and I'm curious if it's known solution, or not.

**Comment by mtrampont** [comment]
I'm the author, but I simply looked at how the `set` command was implemented in `sbt` source code.

**Comment by gslowikowski** [comment]
Thanks.

**Pull request merged**
