### PR TITLE
Fix #440

### LINKED ISSUE #440: sbt-scoverage 2.0.0 fails on Windows with `[error] bad option: -P:scoverage:` errors
We have CIs running on Linux, macOS and Windows.

Since we updated to sbt-scoverage 2.0.0, we have the following error at compile time on Windows when we run the `sbt 'clean;coverage;test;coverageReport'` command:
```scala
[error] bad option: -P:scoverage:dataDir:D:\a\project-name\project-name\modules\common\target\scala-2.13/scoverage-data
[error] bad option: -P:scoverage:sourceRoot:D:\a\project-name\project-name
[error] bad option: -P:scoverage:excludedPackages:caliban.generator.*;com.project.name.api.client.generated.*;com.project.name.api.client.api.testkit.*
[error] bad option: -P:scoverage:reportTestName
[error] four errors found
[error] (common / Compile / compileIncremental) Compilation failed
[error] Total time: 50 s, completed Jun 27, 2022, 11:55:15 AM
```

The same sbt command on Linux and macOS works normally.

Could it be because of the `/scoverage-data` in `scoverage:dataDir:D:\a\project-name\project-name\modules\common\target\scala-2.13/scoverage-data` which should be `\scoverage-data` on Windows 🤔

### PR DESCRIPTION
**Pull request by guizmaii**
Fixes #440

### CODE REVIEW

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Thanks for the pr @guizmaii! I added a commit on top just to ensure that CI would run and also added windows into the CI to see if we could verify this is working. It seems to still have issues:

```
[info] [error] bad option: -P:scoverage:dataDir:C:\Users\runneradmin\AppData\Local\Temp\sbt_50e0e1f6\partB\target\scala-2.13\scoverage-data
[info] [error] bad option: -P:scoverage:sourceRoot:C:\Users\runneradmin\AppData\Local\Temp\sbt_50e0e1f6
[info] [error] bad option: -P:scoverage:reportTestName
[info] [error] bad option: -P:scoverage:dataDir:C:\Users\runneradmin\AppData\Local\Temp\sbt_50e0e1f6\partA\target\scala-2.13\scoverage-data
[info] [error] bad option: -P:scoverage:sourceRoot:C:\Users\runneradmin\AppData\Local\Temp\sbt_50e0e1f6
[info] [error] bad option: -P:scoverage:reportTestName
```

**Comment by guizmaii** [comment]
@ckipp01 Thank you for your help 🙇 

I'll have a look at the issue later today

**Comment by guizmaii** [comment]
I had a look. It seems to be more complicated than I expected. 
The time for me to find the issue would be probably more than I can afford to spend, sadly.

I close the PR, hoping that someone will be able to tackle the issue.

**Comment by ckipp01** [comment]
No worries, thanks for raising the issue!

**Comment by nafg** [comment]
@guizmaii can you share your analysis of the cause, and what the complexity and challenge is?

**Pull request closed without merging**
