### PR TITLE
Make plugin depend on coverageEnabled setting, allow changing runtime scoverage version, add support for Scala.js

### PR DESCRIPTION
**Pull request by lustefaniak**

### CODE REVIEW

**Comment by lustefaniak** [comment]
Required changes to scalac-scoverage-runtime cross compile are here: https://github.com/scoverage/scalac-scoverage-plugin/pull/158

**Comment by vpavkin** [comment]
Am I correct -- this one is waiting for a release of https://github.com/scoverage/scalac-scoverage-plugin that includes https://github.com/scoverage/scalac-scoverage-plugin/pull/158 ?

**Comment by lustefaniak** [comment]
Yes, after cross-compiled scalac-scoverage-plugin is released I can alter
version used in that PR.

pon., 22.08.2016, 11:53 użytkownik Pavkin Vladimir <notifications@github.com>
napisał:

**Comment by gslowikowski** [comment]
@lustefaniak can you contact me via email?

**Comment by gslowikowski** [comment]
@lustefaniak, please create two new seperate PRs based on current repo state:

1. "Add support for scala.js runtime" based on commit
https://github.com/scoverage/sbt-scoverage/pull/166/commits/2c1e7bb979a7a9720841a6222c11e0f18799c65a

2. "Add coveragePluginVersion key" based on commit
https://github.com/scoverage/sbt-scoverage/pull/166/commits/5ce2e347103fd826342d78727bacaf64243c28b8
but use `coverageScalacPluginVersion` key name instead of `coveragePluginVersion`

Remaining commits:
https://github.com/scoverage/sbt-scoverage/pull/166/commits/b91fcc8a11804291308d70a9da376f234151ce81
https://github.com/scoverage/sbt-scoverage/pull/166/commits/9bc108c1d2bf0d0428c5d7312bfabbd83bab9f51
https://github.com/scoverage/sbt-scoverage/pull/166/commits/3c738d2500883a2661f18661ac499707e70d487e
are not required anymore, because this functionality is already merged from #168

**Comment by lustefaniak** [comment]
Added as https://github.com/scoverage/sbt-scoverage/pull/183 and https://github.com/scoverage/sbt-scoverage/pull/184

**Pull request closed without merging**
